feat: add configure Github deployment action
capralifecycle/actions-lib pull request #9
Opened 2024-02-20 11:42 UTC by evan-boone

2024-02-21 11:13 UTC, stekern approved these changes
LGTM 🎉 

It's worth mentioning that the new tests kind of break the testing pattern wrt. isolation as the test for updating a deployment relies on the result of a previous test. It's a bit tricky to avoid here, but it's something I would try to avoid where we can to avoid unnecessarily coupling the tests (e.g., by striving to limit one "arrange-act-assert" instance to a single test case).

2024-02-21 12:38 UTC, evan-boone commented on .github/workflows/tests.yml
> +        id: act-configure-github-deployment-should-fail
Good point. Removing it!

2024-02-22 11:26 UTC, joakimen requested changes
The code looks correct 👍🏻 Just need to consider the workflow permissions for the test workflow.

I do think we are conflating the use of `state` and `status` a bit; according to the [documentation](https://docs.github.com/en/rest/deployments/statuses?apiVersion=2022-11-28#create-a-deployment-status), a deployment may have one or more statuses, and a status has a state (`.deployment.status[].state`). I think it'd be more natural to refer to it as the "deployment status" instead of the "deployment state", as this feels more aligned with the API (in which state is just one of the properties of a status, and not a property of a deployment)

It's subjective though, and not worth the rewrite. Just crossed my mind during review

2024-02-22 11:29 UTC, joakimen commented
Another thing that came up during review is that actionlint complains about several of our actions (parse-config, ..) not having documented output parameters. Will create a task to address that in a separate PR

2024-02-22 12:04 UTC, evan-boone commented on .github/workflows/ci.yml
> -      contents: read
Yes, it seems to be necessary! Adding them again

2024-02-22 12:14 UTC, evan-boone commented
> The code looks correct 👍🏻 Just need to consider the workflow permissions for the test workflow.
> 
> I do think we are conflating the use of `state` and `status` a bit; according to the [documentation](https://docs.github.com/en/rest/deployments/statuses?apiVersion=2022-11-28#create-a-deployment-status), a deployment may have one or more statuses, and a status has a state (`.deployment.status[].state`). I think it'd be more natural to refer to it as the "deployment status" instead of the "deployment state", as this feels more aligned with the API (in which state is just one of the properties of a status, and not a property of a deployment)
> 
> It's subjective though, and not worth the rewrite. Just crossed my mind during review

Good point, but since the only field we actually allow the consumer to configure is the newest state (which is updated through updating a status), I think it is a bit clearer the way it is written now. If we referred to deployment status, it might seem like the action allows all fields belonging to a status object (including f.eks. `description`) to be configured.

2024-02-22 14:00 UTC, joakimen approved these changes

2024-02-22 15:10 UTC, merged